Repository FLAMEGPU/FLAMEGPU2, pull requests merged in 2019-11, with the labels that each got.

#93 General CMake Improvements
  .travis.yml
  CMakeLists.txt
  Doxyfile
  FLAMEGPU2.sln
  README.md
  appveyor.yml
  cmake/common.cmake
  cmake/doxygen.cmake
  examples/mas/CMakeLists.txt
  examples/mas/MAS.vcxproj
  examples/mas/MAS.vcxproj.filters
  examples/simple_example/CMakeLists.txt
  examples/simple_example/simple_example.filters
  examples/simple_example/simple_example.vcxproj
  examples/simple_example/simple_example.vcxproj.filters
  lib/Debug/.gitkeep
  lib/Release/.gitkeep
  scripts/appveyor_install.ps1
  scripts/travis_install.sh
  src/CMakeLists.txt
  src/libflamegpu2.vcxproj
  src/libflamegpu2.vcxproj.filters
  tests/CMakeLists.txt
  tests/tests.vcxproj
  tests/tests.vcxproj.filters
Labels: requires review

#123 Update README, Add CONTRIBUTION, LICENSE, ISSUE TEMPLATES
  .github/bug_report.md
  .github/feature_request.md
  CONTRIBUTING.md
  LICENSE.MD
  README.md
Labels: Documentation

#119 Suggested fix for segfault in simple_example.
  examples/mas/src/main.cu
  include/flamegpu/gpu/CUDAAgentModel.h
  include/flamegpu/gpu/CUDAMessage.h
  src/flamegpu/gpu/CUDAAgentModel.cu
  src/flamegpu/gpu/CUDAMessage.cu
Labels: bug

#159 Curve singleton
  include/flamegpu/gpu/CUDAAgent.h
  include/flamegpu/gpu/CUDAAgentModel.h
  include/flamegpu/gpu/CUDAMessage.h
  include/flamegpu/runtime/agent_function.h
  include/flamegpu/runtime/cuRVE/cuRVEInstance.h
  include/flamegpu/runtime/cuRVE/curve.h
  include/flamegpu/runtime/flamegpu_device_api.h
  include/flamegpu/runtime/messagelist.h
  src/CMakeLists.txt
  src/flamegpu/gpu/CUDAAgent.cu
  src/flamegpu/gpu/CUDAAgentModel.cu
  src/flamegpu/gpu/CUDAMessage.cu
  src/flamegpu/runtime/agent_function.cu
  src/flamegpu/runtime/cuRVE/curve.cu
Labels: requires review

#138 Feature: Host functions - Part 2
  examples/host_functions/src/main.cu
  include/flamegpu/exception/FGPUException.h
  include/flamegpu/flame_api.h
  include/flamegpu/gpu/CUDAAgentModel.h
  include/flamegpu/model/EnvironmentDescription.h
  include/flamegpu/model/ModelDescription.h
  include/flamegpu/runtime/agent_function.h
  include/flamegpu/runtime/cuRVE/cuRVEInstance.h
  include/flamegpu/runtime/cuRVE/curve.h
  include/flamegpu/runtime/flamegpu_device_api.h
  include/flamegpu/runtime/flamegpu_host_api.h
  include/flamegpu/runtime/utility/DeviceEnvironment.cuh
  include/flamegpu/runtime/utility/EnvironmentManager.cuh
  include/flamegpu/runtime/utility/HostEnvironment.cuh
  src/CMakeLists.txt
  src/flamegpu/gpu/CUDAAgentModel.cu
  src/flamegpu/model/EnvironmentDescription.cu
  src/flamegpu/model/ModelDescription.cu
  src/flamegpu/pop/AgentStateMemory.cu
  src/flamegpu/runtime/agent_function.cu
  src/flamegpu/runtime/cuRVE/curve.cu
  src/flamegpu/runtime/flamegpu_host_api.cu
  src/flamegpu/runtime/utility/EnvironmentManager.cu
  src/flamegpu/runtime/utility/HostEnvironment.cu
  tests/CMakeLists.txt
  tests/test_cases/model/test_environment_description.cu
  tests/test_cases/runtime/test_agent_environment.cu
  tests/test_cases/runtime/test_environment_manager.cu
  tests/test_cases/runtime/test_host_environment.cu
Labels: requires review
