Repository FLAMEGPU/FLAMEGPU2, pull requests merged in 2020-10, with the labels that each got.

#383 Fix ambiguity when specifying agent functions by name.
  include/flamegpu/model/LayerDescription.h
  src/flamegpu/model/AgentFunctionData.cpp
  src/flamegpu/model/LayerData.cpp
  src/flamegpu/model/LayerDescription.cpp
  tests/swig/python/model/test_layer.py
  tests/test_cases/gpu/test_cuda_agent_model.cu
  tests/test_cases/gpu/test_cuda_subagent.cu
  tests/test_cases/model/test_layer.cu
  tests/test_cases/runtime/messaging/test_brute_force.cu
Labels: bug, requires review

#386 Bugfix: NVTX marker was missing semicolon.
  src/flamegpu/gpu/CUDASimulation.cu
Labels: bug, hacktoberfest-accepted

#387 RTC include directory detection.
  .gitignore
  cmake/common.cmake
  cmake/version.h
  include/flamegpu/exception/FGPUException.h
  src/CMakeLists.txt
  src/flamegpu/gpu/CUDAAgent.cu
Labels: enhancement, hacktoberfest-accepted

#388 Update github actions to replace deprecated environment modification.
  .github/workflows/Lint.yml
  .github/workflows/Ubuntu.yml
  .github/workflows/Windows.yml
Labels: hacktoberfest-accepted

#390 Add cuda download retrys for windows CI
  scripts/actions/install_cuda_windows.ps1
Labels: hacktoberfest-accepted

#392 Spatial messaging did not account for non-0 minimum environment bounds.
  include/flamegpu/runtime/messaging/Spatial2D/Spatial2DDevice.h
  include/flamegpu/runtime/messaging/Spatial3D/Spatial3DDevice.h
Labels: bug, hacktoberfest-accepted, requires review

#394 Adjust comparison of git sha to support SHA lengths other than 7
  src/flamegpu/gpu/CUDAAgent.cu
Labels: requires review

#405 Invert the NO_SEATBELTS cmake option for usability.
  cmake/common.cmake
  src/CMakeLists.txt
Labels: enhancement, hacktoberfest-accepted

#403 add NO_SEATBELTS block to Curve::getVariableByHash_ldg
  include/flamegpu/runtime/cuRVE/curve.h
Labels: hacktoberfest-accepted

#408 Add NO_SEATBELTS checks to device agent birth/death.
  include/flamegpu/runtime/AgentFunction.h
  include/flamegpu/runtime/flamegpu_device_api.h
  src/flamegpu/gpu/CUDASimulation.cu
  tests/test_cases/exception/test_device_exception.cu
Labels: hacktoberfest-accepted, requires review

#401 Alternate array interface
  include/flamegpu/model/AgentDescription.h
  include/flamegpu/model/EnvironmentDescription.h
  include/flamegpu/model/Variable.h
  include/flamegpu/pop/AgentInstance.h
  include/flamegpu/runtime/flamegpu_host_new_agent_api.h
  include/flamegpu/runtime/utility/EnvironmentManager.cuh
  include/flamegpu/runtime/utility/HostEnvironment.cuh
  swig/python/CMakeLists.txt
  swig/python/flamegpu.i
  tests/swig/python/io/test_io.py
  tests/swig/python/model/test_agent.py
  tests/swig/python/model/test_environment_description.py
  tests/swig/python/model/test_subagent.py
  tests/swig/python/model/test_subenvironment.py
  tests/swig/python/pop/test_agent_instance.py
  tests/swig/python/runtime/test_agent_environment.py
  tests/swig/python/runtime/test_agent_function_conditions.py
  tests/swig/python/runtime/test_agent_state_transition.py
  tests/swig/python/runtime/test_device_agent_creation.py
  tests/swig/python/runtime/test_device_api.py
  tests/swig/python/runtime/test_host_agent_creation.py
  tests/swig/python/runtime/test_host_environment.py
  tests/swig/venv.bat
Labels: hacktoberfest-accepted, requires review

#409 Update environment from add/set to addProperty/setProperty etc
  examples/boids_bruteforce/src/main.cu
  examples/boids_rtc_bruteforce/src/main.cu
  examples/boids_rtc_spatial3D/src/main.cu
  examples/boids_spatial3D/src/main.cu
  examples/circles_bruteforce/src/main.cu
  examples/circles_spatial3D/src/main.cu
  examples/game_of_life/src/main.cu
  examples/host_functions/src/main.cu
  include/flamegpu/model/EnvironmentDescription.h
  include/flamegpu/runtime/flamegpu_device_api.h
  include/flamegpu/runtime/utility/DeviceEnvironment.cuh
  include/flamegpu/runtime/utility/EnvironmentManager.cuh
  include/flamegpu/runtime/utility/HostEnvironment.cuh
  src/flamegpu/gpu/CUDASimulation.cu
  src/flamegpu/io/jsonReader.cpp
  src/flamegpu/io/xmlReader.cpp
  src/flamegpu/model/EnvironmentDescription.cu
  src/flamegpu/runtime/cuRVE/curve_rtc.cpp
  src/flamegpu/runtime/utility/EnvironmentManager.cu
  swig/python/flamegpu.i
  tests/swig/python/io/test_io.py
  tests/swig/python/model/test_environment_description.py
  tests/swig/python/model/test_subenvironment.py
  tests/swig/python/runtime/test_agent_environment.py
  tests/swig/python/runtime/test_environment_manager.py
  tests/swig/python/runtime/test_host_environment.py
  tests/test_cases/exception/test_device_exception.cu
  tests/test_cases/exception/test_rtc_device_exception.cu
  tests/test_cases/io/test_io.cu
  tests/test_cases/model/test_environment_description.cu
  tests/test_cases/model/test_subenvironment.cu
  tests/test_cases/runtime/test_agent_environment.cu
  tests/test_cases/runtime/test_environment_manager.cu
  tests/test_cases/runtime/test_host_environment.cu
  tests/test_cases/runtime/test_rtc_device_api.cu
  tests/test_cases/runtime/test_subenvironment_manager.cu
Labels: hacktoberfest-accepted, requires review

#412 Improve doc comments for host functions/conditions.
  include/flamegpu/model/LayerDescription.h
  include/flamegpu/model/ModelDescription.h
  include/flamegpu/runtime/flamegpu_host_api_macros.h
  src/flamegpu/model/LayerDescription.cpp
  src/flamegpu/model/ModelDescription.cpp
Labels: Documentation
