Repository FLAMEGPU/FLAMEGPU2, pull requests merged in 2020-07, with the labels that each got.

#321 CUDAScanCompaction/CUDAScatter are nolonger singletons
  include/flamegpu/gpu/CUDAAgent.h
  include/flamegpu/gpu/CUDAAgentModel.h
  include/flamegpu/gpu/CUDAAgentStateList.h
  include/flamegpu/gpu/CUDAFatAgent.h
  include/flamegpu/gpu/CUDAFatAgentStateList.h
  include/flamegpu/gpu/CUDAMessage.h
  include/flamegpu/gpu/CUDAMessageList.h
  include/flamegpu/gpu/CUDAScanCompaction.h
  include/flamegpu/gpu/CUDAScatter.h
  include/flamegpu/runtime/AgentFunction.h
  include/flamegpu/runtime/AgentFunctionCondition.h
  include/flamegpu/runtime/flamegpu_device_api.h
  include/flamegpu/runtime/messaging/Array.h
  include/flamegpu/runtime/messaging/Array2D.h
  include/flamegpu/runtime/messaging/Array3D.h
  include/flamegpu/runtime/messaging/BruteForce.h
  include/flamegpu/runtime/messaging/None.h
  include/flamegpu/runtime/messaging/Spatial2D.h
  include/flamegpu/runtime/messaging/Spatial3D.h
  src/flamegpu/gpu/CUDAAgent.cu
  src/flamegpu/gpu/CUDAAgentModel.cu
  src/flamegpu/gpu/CUDAAgentStateList.cu
  src/flamegpu/gpu/CUDAFatAgent.cu
  src/flamegpu/gpu/CUDAFatAgentStateList.cu
  src/flamegpu/gpu/CUDAMessage.cu
  src/flamegpu/gpu/CUDAMessageList.cu
  src/flamegpu/gpu/CUDAScanCompaction.cu
  src/flamegpu/gpu/CUDAScatter.cu
  src/flamegpu/runtime/messaging/Array.cu
  src/flamegpu/runtime/messaging/Array2D.cu
  src/flamegpu/runtime/messaging/Array3D.cu
  src/flamegpu/runtime/messaging/BruteForce.cu
  src/flamegpu/runtime/messaging/Spatial2D.cu
  src/flamegpu/runtime/messaging/Spatial3D.cu
  src/flamegpu/runtime/utility/RandomManager.cu
Labels: requires review

#314 set CMAKE_CUDA_ARCHITECTURES to OFF for CMake 3.18+
  cmake/cuda_arch.cmake
  tests/CMakeLists.txt
Labels: cmake

#331 HostAgentInstance::sort()
  include/flamegpu/gpu/CUDAAgent.h
  include/flamegpu/gpu/CUDAAgentModel.h
  include/flamegpu/gpu/CUDAAgentStateList.h
  include/flamegpu/gpu/CUDAFatAgentStateList.h
  include/flamegpu/gpu/CUDAScatter.h
  include/flamegpu/runtime/flamegpu_host_agent_api.h
  include/flamegpu/runtime/flamegpu_host_api.h
  src/CMakeLists.txt
  src/flamegpu/gpu/CUDAAgent.cu
  src/flamegpu/gpu/CUDAAgentStateList.cu
  src/flamegpu/gpu/CUDAFatAgentStateList.cu
  src/flamegpu/gpu/CUDAScatter.cu
  src/flamegpu/runtime/flamegpu_host_agent_api.cu
  src/flamegpu/runtime/flamegpu_host_api.cu
  tests/CMakeLists.txt
  tests/test_cases/runtime/test_host_agent_sort.cu
Labels: enhancement

#325 Support for multiple CUDAAgentModel instances of same ModelDescription.
  include/flamegpu/gpu/CUDAAgentModel.h
  include/flamegpu/io/factory.h
  include/flamegpu/io/statereader.h
  include/flamegpu/io/statewriter.h
  include/flamegpu/io/xmlReader.h
  include/flamegpu/io/xmlWriter.h
  include/flamegpu/runtime/AgentFunction.h
  include/flamegpu/runtime/AgentFunctionCondition.h
  include/flamegpu/runtime/cuRVE/curve.h
  include/flamegpu/runtime/flamegpu_device_api.h
  include/flamegpu/runtime/utility/EnvironmentManager.cuh
  include/flamegpu/runtime/utility/HostEnvironment.cuh
  include/flamegpu/sim/Simulation.h
  src/flamegpu/gpu/CUDAAgent.cu
  src/flamegpu/gpu/CUDAAgentModel.cu
  src/flamegpu/io/xmlReader.cpp
  src/flamegpu/io/xmlWriter.cpp
  src/flamegpu/runtime/cuRVE/curve.cu
  src/flamegpu/runtime/flamegpu_host_api.cu
  src/flamegpu/runtime/utility/EnvironmentManager.cu
  src/flamegpu/runtime/utility/HostEnvironment.cu
  src/flamegpu/sim/Simulation.cu
  tests/test_cases/gpu/test_cuda_agent_model.cu
  tests/test_cases/runtime/test_environment_manager.cu
Labels: enhancement, requires review

#323 CMake 3.18+ Device Link Xcompiler option fix for Warnings as Errors
  cmake/common.cmake
Labels: cmake, requires review

#336 Fix Visualisation
  include/flamegpu/gpu/CUDAAgent.h
  src/flamegpu/visualiser/AgentVis.cpp
Labels: Priority: High, bug

#338 BugFix: Message output with no agents.
  include/flamegpu/gpu/CUDAMessage.h
  include/flamegpu/runtime/AgentFunction.h
  include/flamegpu/runtime/AgentFunctionCondition.h
  include/flamegpu/runtime/flamegpu_device_api.h
  src/flamegpu/gpu/CUDAAgentModel.cu
  src/flamegpu/gpu/CUDAMessage.cu
  tests/CMakeLists.txt
  tests/test_cases/runtime/messaging/test_brute_force.cu
  tests/test_cases/runtime/messaging/test_messaging.cu
Labels: bug

#343 Read empty messagelist
  include/flamegpu/gpu/CUDAMessage.h
  include/flamegpu/runtime/messaging/Array.h
  include/flamegpu/runtime/messaging/Array2D.h
  include/flamegpu/runtime/messaging/Array3D.h
  include/flamegpu/runtime/messaging/BruteForce.h
  include/flamegpu/runtime/messaging/None.h
  include/flamegpu/runtime/messaging/Spatial2D.h
  include/flamegpu/runtime/messaging/Spatial3D.h
  src/flamegpu/gpu/CUDAAgentModel.cu
  src/flamegpu/gpu/CUDAFatAgentStateList.cu
  src/flamegpu/gpu/CUDAMessage.cu
  src/flamegpu/runtime/messaging/Array.cu
  src/flamegpu/runtime/messaging/Array2D.cu
  src/flamegpu/runtime/messaging/Array3D.cu
  src/flamegpu/runtime/messaging/BruteForce.cu
  src/flamegpu/runtime/messaging/Spatial2D.cu
  src/flamegpu/runtime/messaging/Spatial3D.cu
  tests/test_cases/runtime/messaging/test_array.cu
  tests/test_cases/runtime/messaging/test_array_2d.cu
  tests/test_cases/runtime/messaging/test_array_3d.cu
  tests/test_cases/runtime/messaging/test_brute_force.cu
  tests/test_cases/runtime/messaging/test_spatial_2d.cu
  tests/test_cases/runtime/messaging/test_spatial_3d.cu
  tests/test_cases/runtime/test_agent_function_conditions.cu
Labels: bug, requires review

#327 Remove Appveyor and Travis as CI providers
  .travis.yml
  README.md
  appveyor.yml
  scripts/appveyor_install.ps1
  scripts/travis_install.sh
Labels: CI, on hold

#366 Prevent CMake from trusting symbolic link within Thrust to Cub on Windows.
  cmake/Thrust.cmake
Labels: bug
