Repository FLAMEGPU/FLAMEGPU2, pull requests merged in 2021-04, with the labels that each got.

#489 Proposed fix for #488
  include/flamegpu/model/LayerDescription.h
  src/flamegpu/model/LayerDescription.cpp
  tests/test_cases/model/test_layer.cu
Labels: bug

#501 Improve SWIG exceptions
  swig/python/flamegpu.i
Labels: SWIG

#509 Visualiser Bugfix: Python would not build with visualiser enabled.
  include/flamegpu/visualiser/ModelVis.h
  src/flamegpu/visualiser/ModelVis.cpp
  swig/python/flamegpu.i
Labels: bug

#458 Dependency analysis
  CMakeLists.txt
  examples/boids_bruteforce_dependency_graph/CMakeLists.txt
  examples/boids_bruteforce_dependency_graph/src/main.cu
  include/flamegpu/exception/FGPUException.h
  include/flamegpu/flame_api.h
  include/flamegpu/model/AgentData.h
  include/flamegpu/model/AgentDescription.h
  include/flamegpu/model/AgentFunctionDescription.h
  include/flamegpu/model/DependencyGraph.h
  include/flamegpu/model/DependencyNode.h
  include/flamegpu/model/HostFunctionDescription.h
  include/flamegpu/model/LayerDescription.h
  include/flamegpu/model/ModelData.h
  include/flamegpu/model/ModelDescription.h
  include/flamegpu/model/SubModelDescription.h
  src/CMakeLists.txt
  src/flamegpu/model/DependencyGraph.cpp
  src/flamegpu/model/DependencyNode.cpp
  src/flamegpu/model/HostFunctionDescription.cpp
  src/flamegpu/model/LayerDescription.cpp
  src/flamegpu/model/ModelData.cpp
  src/flamegpu/model/ModelDescription.cpp
  src/flamegpu/model/SubModelDescription.cpp
  swig/python/flamegpu.i
  tests/CMakeLists.txt
  tests/swig/python/model/test_dependency_graph.py
  tests/swig/python/model/test_layer.py
  tests/test_cases/model/test_dependency_graph.cu
Labels: enhancement, optimisation

#322 Example: Sugarscape
  CMakeLists.txt
  examples/sugarscape/CMakeLists.txt
  examples/sugarscape/src/main.cu
Labels: Example, requires review
