Repository FLAMEGPU/FLAMEGPU2, pull requests merged in 2022-08, with the labels that each got.

#794 MessageSpatial2D::In::wrap()
  include/flamegpu/runtime/messaging/MessageSpatial2D.h
  include/flamegpu/runtime/messaging/MessageSpatial2D/MessageSpatial2DDevice.cuh
  include/flamegpu/runtime/messaging/MessageSpatial3D/MessageSpatial3DDevice.cuh
  tests/test_cases/runtime/messaging/test_spatial_2d.cu
  tests/test_cases/runtime/messaging/test_spatial_3d.cu
Labels: enhancement

#903 Bugfix: CUDAEnsemble progress printing nolonger jumps backwards.
  include/flamegpu/sim/SimRunner.h
  src/flamegpu/gpu/CUDAEnsemble.cu
  src/flamegpu/sim/SimRunner.cu
Labels: bug

#882 Pure python agent functions
  CMakeLists.txt
  README.md
  examples/swig_native_python_boids_spatial3D/boids_spatial3D.py
  examples/swig_native_python_boids_spatial3D/venv.bat
  swig/python/CMakeLists.txt
  swig/python/codegen/__init__.py
  swig/python/codegen/codegen.py
  swig/python/flamegpu.i
  swig/python/setup.py.in
  tests/swig/python/codegen/test_codegen.py
  tests/swig/python/codegen/test_codegen_integration.py
Labels: enhancement, python
