Repository FLAMEGPU/FLAMEGPU2, pull requests merged in 2022-11, with the labels that each got.

#930 Windows: CUDAEnsemble can block standby whilst running.
  include/flamegpu/gpu/CUDAEnsemble.h
  src/flamegpu/gpu/CUDAEnsemble.cu
Labels: enhancement, hacktoberfest-accepted

#948 Use of a generic size type
  include/flamegpu/defines.h
  include/flamegpu/gpu/CUDASimulation.h
  include/flamegpu/model/AgentDescription.h
  include/flamegpu/model/EnvironmentDescription.h
  include/flamegpu/model/LayerData.h
  include/flamegpu/model/LayerDescription.h
  include/flamegpu/model/ModelData.h
  include/flamegpu/model/ModelDescription.h
  include/flamegpu/pop/AgentInstance.h
  include/flamegpu/pop/AgentVector.h
  include/flamegpu/pop/AgentVector_Agent.h
  include/flamegpu/runtime/messaging/MessageArray.h
  include/flamegpu/runtime/messaging/MessageArray/MessageArrayDevice.cuh
  include/flamegpu/runtime/messaging/MessageArray2D.h
  include/flamegpu/runtime/messaging/MessageArray2D/MessageArray2DDevice.cuh
  include/flamegpu/runtime/messaging/MessageArray3D.h
  include/flamegpu/runtime/messaging/MessageArray3D/MessageArray3DDevice.cuh
  include/flamegpu/runtime/messaging/MessageBruteForce.h
  include/flamegpu/runtime/messaging/MessageBruteForce/MessageBruteForceDevice.cuh
  include/flamegpu/runtime/messaging/MessageBruteForce/MessageBruteForceHost.h
  include/flamegpu/runtime/messaging/MessageBucket.h
  include/flamegpu/runtime/messaging/MessageBucket/MessageBucketDevice.cuh
  include/flamegpu/runtime/messaging/MessageNone.h
  include/flamegpu/runtime/messaging/MessageSpatial2D.h
  include/flamegpu/runtime/messaging/MessageSpatial2D/MessageSpatial2DDevice.cuh
  include/flamegpu/runtime/messaging/MessageSpatial3D.h
  include/flamegpu/runtime/messaging/MessageSpatial3D/MessageSpatial3DDevice.cuh
  include/flamegpu/runtime/utility/EnvironmentManager.cuh
  include/flamegpu/runtime/utility/HostEnvironment.cuh
  include/flamegpu/runtime/utility/RandomManager.cuh
  include/flamegpu/sim/AgentInterface.h
  include/flamegpu/sim/RunPlan.h
  include/flamegpu/sim/RunPlanVector.h
  include/flamegpu/visualiser/PanelVis.h
  src/flamegpu/model/AgentDescription.cpp
  src/flamegpu/model/EnvironmentDescription.cu
  src/flamegpu/model/LayerData.cpp
  src/flamegpu/model/LayerDescription.cpp
  src/flamegpu/model/ModelData.cpp
  src/flamegpu/model/ModelDescription.cpp
  src/flamegpu/pop/AgentVector.cpp
  src/flamegpu/pop/AgentVector_Agent.cpp
  src/flamegpu/runtime/messaging/MessageArray.cu
  src/flamegpu/runtime/messaging/MessageArray2D.cu
  src/flamegpu/runtime/messaging/MessageArray3D.cu
  src/flamegpu/runtime/messaging/MessageBruteForce.cu
  src/flamegpu/runtime/utility/RandomManager.cu
  swig/python/flamegpu.i
  tests/test_cases/sim/test_RunPlan.cu
  tests/test_cases/sim/test_RunPlanVector.cu
Labels: hacktoberfest-accepted

#958 Fix for python example
  examples/python_boids_spatial3D_wrapped_native/boids_spatial3D.py
Labels: bug

#968 BugFix: Remove redundant code from CUDAFatAgent::addSubAgent()
  src/flamegpu/gpu/CUDAFatAgent.cu
Labels: bug

#988 Fix compilation on Bessemer (GCC11?)
  include/flamegpu/gpu/CUDAAgent.h
  include/flamegpu/io/StateReader.h
  include/flamegpu/io/StateWriter.h
  include/flamegpu/model/ModelDescription.h
  src/flamegpu/io/JSONStateWriter.cpp
  src/flamegpu/io/XMLStateWriter.cpp
  src/flamegpu/pop/AgentVector.cpp
  src/flamegpu/pop/DeviceAgentVector_impl.cu
  src/flamegpu/visualiser/AgentVis.cpp
Labels: bug

#992 CUDAEnsemble truncate log files.
  include/flamegpu/exception/FLAMEGPUException.h
  include/flamegpu/gpu/CUDAEnsemble.h
  include/flamegpu/sim/Simulation.h
  src/flamegpu/gpu/CUDAEnsemble.cu
  src/flamegpu/io/JSONStateWriter.cpp
  src/flamegpu/sim/SimLogger.cu
  src/flamegpu/sim/Simulation.cu
  tests/swig/python/gpu/test_cuda_ensemble.py
  tests/swig/python/gpu/test_cuda_simulation.py
  tests/test_cases/gpu/test_cuda_ensemble.cu
  tests/test_cases/gpu/test_cuda_simulation.cu
Labels: enhancement

#285 Enable ctest for C++ test executable(s)
  CMakeLists.txt
  README.md
  tests/CMakeLists.txt
Labels: cmake

#1002 Duplicate several C ensemble tests for RTC.
  tests/test_cases/gpu/test_cuda_ensemble.cu
Labels: Tests, RTC
